blank_issues_enabled: true
contact_links:
  - name: RuyiSDK Official Website
    about: RuyiSDK 官方网站
    url: https://ruyisdk.org/
  - name: RuyiSDK Discussions
    about: RuyiSDK 讨论区
    url: https://ruyisdk.cn/c/ruyisdk/9
